-- AlterTable
ALTER TABLE "guests" ALTER COLUMN "lastActivityAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "expiresAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "endedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "orders" ALTER COLUMN "estimatedReadyAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "restaurant_tables" ALTER COLUMN "occupiedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastActivityAt" SET DEFAULT CURRENT_TIMESTAMP;
